### ISSUE TITLE
Link no longer works

### ISSUE THREAD

**Issue by ghost** [SlyBouhafs/sn-theme-dracula#10]
The install link for this theme no longer works. I believe there are some changes on SN side that need to be accounted for. 
![image](https://user-images.githubusercontent.com/50109194/143767195-86d24790-a910-444e-a353-bd6e22fda125.png)

**Comment by suprkain** [comment]
Same message for me as well.

**Comment by suprkain** [comment]
> 

I want to add that I tried that link in the desktop app and it worked fine.
