### ISSUE TITLE
Migrate from raw.githubusercontent.com

### ISSUE THREAD

**Issue by arielsvg** [SlyBouhafs/sn-theme-dracula#2]
Hey there 👋

Just a heads up that because raw.githubusercontent.com doesn't handle [preflight requests](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request), you won't be able to install the theme from a web platform. If you want your theme to be install-able from everywhere you'll want to move the extension JSON file somewhere else. Of course if you don't mind feel free to close this ticket, just thought you should know :)

**Comment by SlyBouhafs** [comment]
Hey, thanks for the heads up! 
I mainly use the desktop app so i didn't encounter such an issue, i will move it to jsdelivr cdn to make sure web users can install the theme too!
