### ISSUE TITLE
Update ext.json version and download URL

### ISSUE THREAD

**Issue by CarnageDevs** [SlyBouhafs/sn-theme-dracula#20]
With the release of 2.0.0, the current ext.json version is still set to 0.0.18 and the `"url"` and `"download_url"` fields still point to the previous version, 0.0.18. They need to be updated to 2.0.0 for users to be able to receive the update.

In addition, the install link on [https://draculatheme.com/standard-notes](url) should be updated to point to the new ext.json ([https://cdn.jsdelivr.net/gh/dracula/standard-notes@master/ext.json](url))

**Comment by SlyBouhafs** [comment]
Hey @CarnageDevs! Thanks for opening an issue!
I fixed the version number! For the install instructions, they are actually up to date, you can check it out here https://github.com/dracula/standard-notes/blob/master/INSTALL.md I am not entirely sure why it didn't get reflected on the website. Will try to look into it once i get some time!

**Comment by CarnageDevs** [comment]
Thanks for the prompt response, I can confirm the theme has been successfully updated and I have the new version applied on SN now!

Feel free to close this issue once you resolve the outdated URL on the website!

**Comment by SlyBouhafs** [comment]
Hey @zenorocha, sorry for the notification.
Do you have any idea why the [draculatheme.com/standard-notes](https://draculatheme.com/standard-notes) webpage didn't get updated with the new [README.md](https://github.com/dracula/standard-notes/blob/master/README.md) and [INSTALL.md](https://github.com/dracula/standard-notes/blob/master/INSTALL.md) files?

**Comment by SlyBouhafs** [comment]
The issue has been fixed.
