### ISSUE TITLE
Tags & Views display white on white

### ISSUE THREAD

**Issue by WeberAlex** [SlyBouhafs/sn-theme-dracula#22]
Hello,

I am having an issue with the [Dracula Theme](https://cdn.jsdelivr.net/gh/dracula/standard-notes@master/ext.json) in Standard Notes.

Standard Note: 3.4.0.
Chrome: 103
Windows: 11 Pro

The Tags and the Views on the left pane display white on white when I click on them, see below:

![image](https://user-images.githubusercontent.com/28292190/178140454-f97163a5-db25-4eec-9e61-a366742a06cd.png)

**Comment by Galactix** [comment]
Same issue

**Comment by SlyBouhafs** [comment]
Fixed in #21
