### ISSUE TITLE
Search contrast

### ISSUE THREAD

**Issue by julianfairfax** [SlyBouhafs/sn-theme-dracula#24]
Hi, I'm loving this theme, but the contrast on the search here really stands out. Could something be done about it to blend in a bit more?

![image](https://user-images.githubusercontent.com/43753131/184532372-b3aea448-3017-4d0b-ba03-c9a77a5df03f.png)

**Comment by SlyBouhafs** [comment]
Hey @julianfairfax, thanks for opening an issue!
Where is that search located? It doesn't look like the search dialog i have. 
Can you provide more information?

**Comment by julianfairfax** [comment]
> Hey @julianfairfax, thanks for opening an issue! Where is that search located? It doesn't look like the search dialog i have. Can you provide more information?

On the sidebar. This is the latest version of the Standard Notes website so you should have the same phone.

**Comment by julianfairfax** [comment]
@SlyBouhafs Have you been able to reproduce this?
