### ISSUE TITLE
Dracula Theme Not Working on Mobile App

### ISSUE THREAD

**Issue by vkeerthivikram** [SlyBouhafs/sn-theme-dracula#25]
It says the theme is not available on mobile.

**Comment by nrkallen** [comment]
I went into the setting and opted in for the new mobile experience, it brought the theme over automagically for me!

**Comment by vkeerthivikram** [comment]
> I went into the setting and opted in for the new mobile experience, it brought the theme over automagically for me!

Done, it works now. Thanks
