### ISSUE TITLE
[Web/Desktop] The version number of the app is a bit difficult to read

### ISSUE THREAD

**Issue by JaspalSuri** [SlyBouhafs/sn-theme-dracula#3]
I'm not sure if this is an issue with the app or the theme, but I wasn't able to "reproduce" the issue when the Futura Theme and other dark themes were applied. 

Here's what it looks like in the Focus theme: 
![image](https://user-images.githubusercontent.com/44656000/95834968-7fc26f80-0cf2-11eb-8699-a41cdfdc1ad0.png)

Here's what it looks like in the Dracula theme:
![image](https://user-images.githubusercontent.com/44656000/95835004-8b159b00-0cf2-11eb-99d5-863534615147.png)

That said, I wanted to say thanks for working on this theme. I used to have Futura as my default theme before it.

**Comment by SlyBouhafs** [comment]
Hey! Thanks for using the theme, I really appreciate it!

You're right, the font color isn't bright enough, I updated the color in the new 0.0.11 version, it should be good now.

Let me know if you see any new issues!

**Comment by JaspalSuri** [comment]
Thanks for the fix! The theme didn't auto-update, but I reinstalled it, deactivated & reactivated it, and it looks good! 

I think it might be because the latest version number  (0.1.1) is "smaller" than the previous version (1.2.3).

**Comment by SlyBouhafs** [comment]
Reopening since the new update that closes #4 breaks the version color again.
