### ISSUE TITLE
[Web/Desktop] When the passcode lock is enabled and the user hits enter, the submission button turns white.

### ISSUE THREAD

**Issue by JaspalSuri** [SlyBouhafs/sn-theme-dracula#4]
[Here's](https://imgur.com/a/YgwK32x) what it looks like on my end.

**Comment by SlyBouhafs** [comment]
Hey!

This is a weird bug! I couldn't reproduce it on my end, are you on the beta version?

**Comment by JaspalSuri** [comment]
You're right! Sorry about that. There might be some more changes made to the passcode lock, which might coincidentally fix the issue.

**Comment by JaspalSuri** [comment]
I forgot the mention that the other themes (both first and third-party) aren't affected. Can you try [reinstalling the theme](https://cdn.jsdelivr.net/gh/slybouhafs/sn-theme-dracula/sn-theme-dracula.json) to see if you can reproduce it once more? 

I also see this when trying to uninstall the extension. 
![image](https://user-images.githubusercontent.com/44656000/96330793-236e9100-100d-11eb-9c48-7eb1a4dbb016.png)

**Comment by SlyBouhafs** [comment]
Hey!

I did reinstall the theme and couldn't replicate the issue. Actually, i don't have that dialogue popup when i want to delete a theme, instead, i have the system UI. Here, this is how the window looks on my side:

![Screen Shot 2020-10-20 at 04 37 30](https://user-images.githubusercontent.com/1410462/96537367-009edf80-128e-11eb-84c9-f9e0b7ad482a.png)

Can you provide more info? Is that the electron app you're running? What OS are you on? Do you use chrome as your browser? It would help a lot if you gave me more info so i can get a deep look at it.

**Comment by JaspalSuri** [comment]
I apologize for not providing more info!

I am viewing the theme in the latest desktop beta for macOS, however, I can replicate the issue in the latest stable and beta web app in Microsoft Edge. Perhaps if you try signing out, it will show a prompt using the app's UI instead (based on my testing inside of the browser).  

![image](https://user-images.githubusercontent.com/44656000/96559050-67fa6680-1271-11eb-9d38-959aafced968.png)

**Comment by SlyBouhafs** [comment]
Finally, I was able to reproduce, the bug started happening after the last commit where i switched the colors to make the software version a bit brighter. I'll revert the changes back.
I will think of a better way to style the software version.
