### ISSUE TITLE
Theme is inconsistent across different Standard Notes clients

### ISSUE THREAD

**Issue by JJGadgets** [SlyBouhafs/sn-theme-dracula#7]
The color scheme for Dracula theme appears to be different across clients, even though they're signed in with the same account, and thus have the same copies of the extension downloaded. I've tried it on my Windows desktop, my MacBook Pro on Catalina, my ThinkPad running Linux (PopOS GNOME), and my iPhone 8 on iOS 13.7, and they all appear different, as shown in the attached screenshots.
I am using the Standard Notes Org Mode editor.

This is the Windows 1809 LTSC screenshot.
![image](https://user-images.githubusercontent.com/5709019/111862436-51774900-8990-11eb-8b64-de8d5982a686.png)

This is the MacBook Pro macOS Catalina screenshot.
![image](https://user-images.githubusercontent.com/5709019/111862457-66ec7300-8990-11eb-93fd-59d5217075cc.png)

This is the PopOS 20.10 GNOME 3.38 (Xorg) screenshot.
![image](https://user-images.githubusercontent.com/5709019/111862473-766bbc00-8990-11eb-9106-7a35aa8263a0.png)

This is the iPhone 8 iOS 13.7 screenshot.
![image](https://user-images.githubusercontent.com/5709019/111862640-8637d000-8991-11eb-9ae5-e7973683667b.png)

According to Doom Emacs, the colors are only accurate on the PopOS setup, as shown below.
![image](https://user-images.githubusercontent.com/5709019/111862649-951e8280-8991-11eb-9023-dbb9f5d8f4c2.png)

**Comment by SlyBouhafs** [comment]
Hi @JJGadgets, sorry for the delay, isn't this related to each OS color profile?
Does the official Dracula website look the same across all devices/browser?

**Comment by SlyBouhafs** [comment]
Closing the issue for now, feel free to open again.
