### ISSUE TITLE
JSDeliver files still point to old repo

### ISSUE THREAD

**Issue by EweSparky** [SlyBouhafs/sn-theme-dracula#8]
https://cdn.jsdelivr.net/gh/dracula/standard-notes/sn-theme-dracula.json contains the following:

`"latest_url": "https://cdn.jsdelivr.net/gh/slybouhafs/sn-theme-dracula/sn-theme-dracula.json",`

even though `sn-theme-dracula.json` in this repo has been to:

`"latest_url": "https://cdn.jsdelivr.net/gh/dracula/sn-theme-dracula/sn-theme-dracula.json",`

It looks like that file was updated without a new release, so JSDeliver won't pull in the change.

**Comment by SlyBouhafs** [comment]
Hi @StuartMorrisAU, sorry for the delay, thanks for opening an issue.
Even though the urls in the json file are outdated, they should work nonetheless.

I'll push an update to fix it.
